const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Твёрдый: 0},
	{Земля: 0},
	{Фон: 0},
	{КнопкаИграть: 0},
	{Название: 0},
	{Якорь: 0},
	{кВАДРАТ: 0},
	{КнопкаПравило: 0},
	{КнопкаВыход: 0},
	{Компания: 0},
	{Мышь: 0},
	{КнопкаНазад: 0},
	{Браузер: 0},
	{Правило: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Петя: 0},
	{Синусоида: 0},
	{Робот: 0},
	{Шипы: 0},
	{Монета: 0},
	{Пуля: 0},
	{СИНИЙУЧЕБНИК: 0},
	{кРАСНЫЙУЧЕБНИК: 0},
	{Клавиатура: 0},
	{Монеты: 0},
	{Вода: 0},
	{Флаг: 0},
	{БоссРобот: 0},
	{Сфера: 0},
	{Hp: 0},
	{Победа: 0},
	{Аудио: 0},
	{HP: 0}
];

self.InstanceType = {
	Земля: class extends self.ISpriteInstance {},
	Фон: class extends self.ISpriteInstance {},
	КнопкаИграть: class extends self.ISpriteInstance {},
	Название: class extends self.ITextInstance {},
	кВАДРАТ: class extends self.ISpriteInstance {},
	КнопкаПравило: class extends self.ISpriteInstance {},
	КнопкаВыход: class extends self.ISpriteInstance {},
	Компания: class extends self.ITextInstance {},
	Мышь: class extends self.IInstance {},
	КнопкаНазад: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	Правило: class extends self.ITextInstance {},
	Петя: class extends self.ISpriteInstance {},
	Робот: class extends self.ISpriteInstance {},
	Шипы: class extends self.ISpriteInstance {},
	Монета: class extends self.ISpriteInstance {},
	СИНИЙУЧЕБНИК: class extends self.ISpriteInstance {},
	кРАСНЫЙУЧЕБНИК: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	Монеты: class extends self.ITextInstance {},
	Вода: class extends self.ISpriteInstance {},
	Флаг: class extends self.ISpriteInstance {},
	БоссРобот: class extends self.ISpriteInstance {},
	Сфера: class extends self.ISpriteInstance {},
	Hp: class extends self.ISpriteInstance {},
	Победа: class extends self.ITextInstance {},
	Аудио: class extends self.IInstance {}
}